### ISSUE TITLE
Paths are getting corrupted when using "--remote-option" with popt 1.19

### ISSUE THREAD

**Issue by zickgraf** [RsyncProject/rsync#408]
With popt 1.19, paths might get corrupted.

Steps to reproduce (important: do not delete the **--dry-run**!):

```
$ mkdir /tmp/test1; mkdir /tmp/test2; touch /tmp/test1/test_file
$ rsync -aAX  --info=backup,copy,del,name --remote-option="-v" /tmp/test1/ /tmp/test2/ --dry-run
```

Expected output:
```
./
test_file
```

Actual output:
```
created directory \#001
./
test_file
```

Due to the bogus directory, the target seems to default to the current directory. So executing the above command without "--dry-run" will sync `/tmp/test1/` to the current directory.

Relevant excerpt from the [release notes of popt 1.19](http://lists.rpm.org/pipermail/rpm-announce/2022-September/000100.html):

> One noteworthy item is a memory leak fix which can affect 
> callers, in particular some applications have been relying on 
> poptGetArg() returned strings persisting over poptResetContext() call.

Relevant GitHub issue mentioning other affected packages: https://github.com/rpm-software-management/popt/issues/80

**Comment by WayneD** [comment]
Indeed. With popt 1.19 it has started to free argv values that rsync relied upon remaining allocated.  I've committed a change that duplicates the argv array for every `parse_arguments()` caller. The use of `--remote-args` triggered this because it calls back into the arg parser, and thus triggered the arg corruption.  In looking at other multi-callers of `parse_arguments()` (such as `--protect-args` and daemon mode), it looks like it is only the `--remote-args` sequence that would have resulted in the arg corruption.  In any case, my latest code should fix any issues for all callers.

**Comment by zickgraf** [comment]
Thanks for the quick fix! I can confirm that the problems disappear when using the latest master.

Shall I close the issue or do you want to keep it open until the fix is released?

**Comment by WayneD** [comment]
I'm currently leaving these open until release, though I guess I should add a fixed label to my arsenal.
